id: P00A4DF64
initial_creation_type: input
source_metadata:
  title: Swift Rebirth Prayers
  language: bo
  description: 'A selection of prayers for the swift rebirth (myur byon gsol ’debs)
    of prominent individuals (arranged alphabetically by subject):'
  volume:
    e98c6700d9b04e23b4ba5a045ecc6e58:
      title: 'The Swift Fulfilment of Wishes: A Prayer for the Swift Return of the
        Supreme Tulku of the Fifth Drubwang Dzogchen Rinpoche'
      parent: Fifth Dzogchen Rinpoche
    2297e31526c74c18bec07553854c31a6:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    2908bc3e548c49db8f95b53465fa748a:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé
        Palzangpo
      parent: Fourth Dodrupchen Rinpoche
    2c2fe6a9df524869814d9e8c58a70088:
      title: Prayer for the Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    974c65dbea2a488bbc63890921bdeb8e:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Fourth Dodrupchen Rinpoche
    96311315902e4ef4a3556d045223ea49:
      title: 'The Moonlight of Auspiciousness: A Yearning Prayer to the Noble and
        Glorious Guru Combined with an Aspiration for His Swift Return'
      parent: Gyurme Tsewang Gyatso
    a34ddb5663cc4aa7b8313a9f75e6f215:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Jamgön Kongtrul Lodrö Thaye
    e7e432a1abb44b91905cbe2a1bac0a98:
      title: Prayer for the Swift Rebirth of Jamyang Khyenrab Tayé
      parent: Jamyang Khyenrab Tayé
    2a00adc475d04fc19a0024636734510c:
      title: Lamenting Prayer to Jamyang Chökyi Lodrö
      parent: Jamyang Khyentse Chökyi Lodrö
    2e037231dc634977b4cfe8e4d7db4c69:
      title: 'Wondrous Light of the Moon: A Prayer for the Swift Appearance of the
        Supreme Tulku of Vajradhara'
      parent: Jamyang Loter Wangpo
    2e67c209f433489c91b218fa17c1df03:
      title: 'The Swift Fulfilment of Wishes: Prayer for the Swift Appearance of the
        Supreme Tulku of the Mañjughoṣa Guru'
      parent: Katok Situ Chökyi Gyatso
    c7296430d89e461283f10b98e14ac89c:
      title: 'Cymbals to Invoke a Compassionate Response: A Prayer for Swift Rebirth
        of Khandro Tsering Chödrön'
      parent: Khandro Tsering Chödrön
    fd479a8d4f104150acaa98700fab4dd7:
      title: 'The Swift Infusion of Blessings: A Lament and Prayer to Invoke the Wisdom
        Mind of Khenchen Vāgindra on the Occasion of His Passing into the Great Peace
        of the Dharmadhātu'
      parent: Ngawang Samten Lodrö
    0e5524d5924b4912a7c0afaba6e17df1:
      title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
      parent: Tenpai Nyima Rinpoche
    f48ac01a155c41ca87554b7d66cb4d3a:
      title: 'The Tambura of Devotion: A Prayer for the Swift Appearance of the Supreme
        Tulku of the All-Seeing Conqueror and Cardinal Guardian of the Land of Snows'
      parent: Thirteenth Dalai Lama
    4ced270255dc4cfb94ede1b53c41468f:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Trulshik Rinpoche
created_at: '2022-03-01T05:59:59.961421'
last_modified_at: '2022-03-01T05:59:59.961424'
statistics:
  total_words: 4024
  total_non_words: 321
quality:
  non_words_ratio: 0.08
